name = "transitcares"
main = "workers/auth-jwt.ts"
compatibility_date = "2024-09-01"

[vars]
FIRECRAWL_API_KEY = ""
FIRECRAWL_URL = "https://api.firecrawl.dev/v1/crawl"
API_TOKEN = "Y9Pvv7FwV-2r6OCMQuyFAsTJ6VEbLKGOK8JymBsux_M"
AUTH_JWT_SECRET = "MjnPedAf7Un6mznddPUh2itIvBsTzTkG9qrMgbYyZTYmm9CyucHC0VZDyWDVYWtOfusbHaYiyo9jobdGLfvd-g"
ADMIN_EMAILS = "getfunedu@gmail.com"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ajo-safe-ride-uploads"
